"""Initial migration

Revision ID: b64e4b794750
Revises: 
Create Date: 2026-03-18 18:23:18.733149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import api.db.models


# revision identifiers, used by Alembic.
revision: str = 'b64e4b794750'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.Column('urls_found', sa.Integer(), nullable=False),
    sa.Column('broken_links_count', sa.Integer(), nullable=False),
    sa.Column('missing_security_headers', sa.Integer(), nullable=False),
    sa.Column('is_ssl_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_results', api.db.models.JSONDict(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanrecord_target_url'), 'scanrecord', ['target_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanrecord_target_url'), table_name='scanrecord')
    op.drop_table('scanrecord')
    # ### end Alembic commands ###
